package router

type MessageBody struct{
	Message string 
	To int8

}
func SendSingleMessage(body MessageBody)(){

// EAAO6q8TAwwABOZCufYc6YtSzazeLCZCH4dZCClZC24ZBS6fHjRIXCF4IZB5cCrd4tZCiUvVdWA99TDvk41ctrqRgN1g7fJSVI3h02V3aeOU6RZAfumjhEKQaxtgxibHEbyqmgPlvX9pFAsILAYZAUAsWq6Bi7PZAvNLUbYMzVW7ZBxSZB12KZApcCPo8fova4THZBWzt3sxFlUOjWVlrAvZBrjMyTH6B0mis8tsVdA1
}